compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
